// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GD.Core.Localization
{
    
    
    public partial class Localization
    {
        
        private static string _ID_6a2549080d0a439885e5651910661c37 = "6a254908-0d0a-4398-85e5-651910661c37";
        
        private static string _ID_84c8ff6755e74be68dc5aae8d8fe3fb7 = "84c8ff67-55e7-4be6-8dc5-aae8d8fe3fb7";
        
        public static string EncounterContinue
        {
            get
            {
                return GD.Core.Localization.Localization.GetStringById(GD.Core.Localization.Localization._ID_6a2549080d0a439885e5651910661c37);
            }
        }
        
        public static string QuitMessage
        {
            get
            {
                return GD.Core.Localization.Localization.GetStringById(GD.Core.Localization.Localization._ID_84c8ff6755e74be68dc5aae8d8fe3fb7);
            }
        }
    }
}
